### ISSUE TITLE
Flutter run output not showing on floating window : Termux-X11 problem

### ISSUE THREAD

**Issue by mdHABIBURRAHMANHABIB1** [mumumusuc/Flutter-Termux#1]
![display_problem](https://github.com/mumumusuc/Flutter-Termux/assets/142384619/c2632405-d7ea-4bea-80a4-3ef4bc8c4d6b)

- how you get output on floating window
- this is Termux-X11 official app . but i see your app is deferent.
- can you plz provide you apps link or tut how can i get that?

Thanks in Advance.

**Comment by mumumusuc** [comment]
+ I am using the Termux-X11 app too, floating window is OS feature(HarmonyOS)
+ Termux-X11 has PIP mode, it just work (**badly**)
+ edit `linux/my_application.cc` under your project, change gtk window size to fit your device, `500x740` is perfect for me(Termux-X11 scaled 200%).
```
$ vi linux/my_application.cc +50
- gtk_window_set_default_size(window, 1080, 720);
+ gtk_window_set_default_size(window, 500, 740);
```

**Comment by bdloser404** [comment]
> * I am using the Termux-X11 app too, floating window is OS feature(HarmonyOS)
> * Termux-X11 has PIP mode, it just work (**badly**)
> * edit `linux/my_application.cc` under your project, change gtk window size to fit your device, `500x740` is perfect for me(Termux-X11 scaled 200%).
> 
> ```
> $ vi linux/my_application.cc +50
> - gtk_window_set_default_size(window, 1080, 720);
> + gtk_window_set_default_size(window, 500, 740);
> ```

Oh thats Spit Window. i already edit GTK window default size according to my default screen size. but sadly not everyphone has spilt window feature. but we can use third party apps.

Although great work.
